# sal_hora = float(input("Quanto você ganha por hora? R$ "))
# horas_trab = float(input("Quantas horas você trabalhou no mês? "))
# salario_bruto = sal_hora * horas_trab
# IR = salario_bruto * 0.11
# INSS = salario_bruto * 0.08
# sindicato = salario_bruto * 0.05
# salario_liquido = salario_bruto - (IR + INSS + sindicato)
# Print:(f"a) Pago ao IR: R$ {IR:.2f}")
# Print:(f"b) Pago ao INSS: R$ {INSS:.2f}")
# Print:(f"c) Pago ao sindicato: R$ {sindicato:.2f}")
# Print:(f"d) Salário líquido: R$ {salario_liquido:.2f}")



